// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iioklotlfyeifiezxqkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb2tsb3RsZnllaWZpZXp4cWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDU4MjgsImV4cCI6MjA1Nzg4MTgyOH0.y_aT33wOJxcM5FK8V2xJRjLNmyTbFm6fxui494NMFMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);